### ISSUE TITLE
Address not saved into address book after checkout

### ISSUE THREAD

**Issue by asecondwill** [silvershop/silvershop-core#596]
After checkout, i end up on a order view page with a menu,  

My Account
Past Orders
Edit Profile
Address Book
Log Out

Address book shows no addresses.  It should have the one I entered as the shipping (and billing) address.

**Comment by bummzack** [comment]
What version of shop are you using? Are you using any additional modules?

I just tested using shop 2.2.1 and it works as expected.

**Comment by asecondwill** [comment]
composer file:

````
{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"php": ">=5.5",
		"silverstripe/cms": "3.5.3",
		"silverstripe/framework": "3.5.3",
		"silverstripe/reports": "3.5.3",
		"silverstripe/siteconfig": "3.5.3",
		"silvershop/core": "2.1.1",
		"omnipay/stripe": "^2.4",
		"bummzack/silverstripe-omnipay-ui": "^0.1.1",
		"silverstripe/blog": "^2.4",
		"heyday/silverstripe-menumanager": "~2.1.0",
		"unclecheese/zen-fields": "^1.0",
		"bummzack/sortablefile": "^1.2",
		"silverstripe-australia/addressable": "dev-master",
		"silverstripe/userforms": "*",
		"undefinedoffset/sortablegridfield": "*",
		"silvershop/discounts": "*",
		"jonom/focuspoint": "^2.4",
		"jonom/silverstripe-betternavigator": "^2.1",
		"silvershop/shipping": "master",
		"froog/silvergraph" : "master"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~3.7@stable"
	},
	"extra": {
		"branch-alias": {
			"3.x-dev": "3.5.x-dev"
		}
	},
	"config": {
		"process-timeout": 600
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}
````

**Comment by asecondwill** [comment]
Could you share the _shop.yml of your test shop please.

**Comment by asecondwill** [comment]
ok, fresh install.  simple theme

````
{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"php": ">=5.3.3",
		"silverstripe/cms": "3.5.3",
		"silverstripe/framework": "3.5.3",
		"silverstripe/reports": "3.5.3",
		"silverstripe/siteconfig": "3.5.3",
		"silverstripe-themes/simple": "3.1.*",
		"silvershop/core": "^2.2",
		"omnipay/stripe": "^2.4",
		"bummzack/silverstripe-omnipay-ui": "^0.1.1"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~3.7@stable"
	},
	"extra": {
		"branch-alias": {
			"3.x-dev": "3.5.x-dev"
		}
	},
	"config": {
		"process-timeout": 600
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}

````

**Comment by asecondwill** [comment]
````
---
Name: app
After: silvershop/config#shopconfig
---
CheckoutConfig:
  member_creation_enabled: true
  membership_required: true

Email:
  admin_email: example@example.com

i18n:
  default_locale: en_NZ

Order:
  modifiers:
    - 'SimpleShippingModifier'
    - 'FlatTaxModifier'
  cancel_before_payment: false
  cancel_before_processing: false
  cancel_before_sending: false
  cancel_before_sending: false
  cancel_after_sending: false
  # Change / add order status, added Refunded
  db:
    Status: Enum('Unpaid,Paid,Processing,Refunded,Sent,Complete,AdminCancelled,MemberCancelled,Cart','Cart')
  # For logging order status changes & emailing notifications to customers
  log_status:
    - Processing
    - Sent
    - MemberCancelled
    - AdminCancelled

OrderActionsForm:
  # allow_paying: false # disable prompt to pay an unpaid order on the AccountPage
  # allow_cancelling: true # allow cancelling of an order on the AccountPage
  email_notification: true  # Send email upon cancellation of an order

OrderManipulation:
  allow_cancelling: true
  allow_paying: true

#OrderProcessor:
#  send_confirmation: true  #send order confirmation when an order is placed, but unpaid
#  send_admin_notification: true  # copy to admin

Product:
  global_allow_purchase: false
  # length_unit: 'M'
  # weight_unit: 'Pounds'
  db: # Revised decimal places
    CostPrice: 'Currency(19,2)'
    BasePrice: 'Currency(19,2)'
    Weight: 'Decimal(12,3)'
    Height: 'Decimal(12,3)'
    Width: 'Decimal(12,3)'
    Depth: 'Decimal(12,3)'

# Change the dimensions of product thumbnails
Product_Image:
  thumbnail_width: 140
  thumbnail_height: 100
  content_image_width: 200
  large_image_width: 200

ProductCategory:
  include_child_groups: true
  must_have_price: true
  sort_options:
    'Title' : 'Alphabetical'
    'Price' : 'Lowest Price'

ShopConfig:
  base_currency: 'NZD'
  email_from: sales@myshop.com
  receipt_subject: "Thank you for your order at www.myshop.com - Order #%d"

ShopCurrency:
  decimal_delimiter: '.'
  thousand_delimiter: ','
  # european style currencies, e.g. 45,00 € instead of €45,00
  append_symbol: true

ShoppingCart_Controller:
  # Redirect to the cart page after manipulating the shopping cart
  direct_to_cart_page: true
  # disable security token for cart-links
  disable_security_token: true

CheckoutPage:
    steps:
        'membership' : 'CheckoutStep_Membership'
        'contactdetails' : 'CheckoutStep_ContactDetails'
        'shippingaddress' : 'CheckoutStep_Address'
        'billingaddress' : 'CheckoutStep_Address'
        'paymentmethod' : 'CheckoutStep_PaymentMethod'
        'summary' : 'CheckoutStep_Summary'

````
