### ISSUE TITLE
Incorrect Documentation re Shipping Method

### ISSUE THREAD

**Issue by gordonbanderson** [silvershop/silvershop-core#667]
I copied config from the page https://github.com/silvershop/silvershop-core/blob/master/docs/en/02_Customisation/01_Recipes/Multi_Step_Checkout.md

I had to comment out the shipping method line in order to get a dev/build to work

```
SilverShop\Page\CheckoutPage:
  steps:
    membership: 'SilverShop\Checkout\Step\Membership'
    contactdetails: 'SilverShop\Checkout\Step\ContactDetails'
    shippingaddress: 'SilverShop\Checkout\Step\AddressBook'
    billingaddress: 'SilverShop\Checkout\Step\AddressBook'
 #   shippingmethod: 'SilverShop\Checkout\Step\ShippingMethod'
    summary: 'SilverShop\Checkout\Step\Summary'
```
